// apps/cli/src/tui/App.tsx
import type { Device, IBus } from '@emdzej/ibusx-core'
import { Box, useApp, useInput } from 'ink'
import { type ReactElement, useEffect, useState } from 'react'
import type { DeviceEntry } from '../registry.js'
import { appendLog, attachBusListeners } from './bus.js'
import { DeviceList } from './components/DeviceList.js'
import { EventLog } from './components/EventLog.js'
import { Footer } from './components/Footer.js'
import { StatePane } from './components/StatePane.js'
import { type LogEntry, nextLogId } from './log.js'

interface AppProps {
  bus: IBus
  port: string
  entries: readonly DeviceEntry[]
  // biome-ignore lint/suspicious/noExplicitAny: heterogeneous generics
  devices: readonly Device<any, any>[]
}

type Focus = 'devices' | 'controls'

export function App({ bus, port, entries, devices }: AppProps): ReactElement {
  const { exit } = useApp()
  const [selectedDevice, setSelectedDevice] = useState(0)
  const [selectedControl, setSelectedControl] = useState(0)
  const [focus, setFocus] = useState<Focus>('devices')
  const [active, setActive] = useState(false)
  const [status, setStatus] = useState('idle')
  const [log, setLog] = useState<readonly LogEntry[]>([])

  useEffect(() => {
    const detach = attachBusListeners(bus, devices, (entry) => {
      setLog((prev) => appendLog(prev, entry))
    })
    setLog((prev) =>
      appendLog(prev, {
        id: nextLogId(),
        kind: 'system',
        ts: Date.now(),
        message: `listening on ${port}`,
      }),
    )
    return detach
  }, [bus, devices, port])

  const currentEntry = entries[selectedDevice]
  const currentDevice = devices[selectedDevice]
  const controlEntries = currentEntry ? Object.entries(currentEntry.controls) : []

  useInput((input, key) => {
    if (input === 'q' || (key.ctrl && input === 'c')) {
      exit()
      return
    }
    if (input === 'a') {
      const next = !active
      setActive(next)
      for (const d of devices) d.mode = next ? 'active' : 'passive'
      return
    }
    if (key.tab) {
      setFocus((f) => (f === 'devices' ? 'controls' : 'devices'))
      return
    }
    if (focus === 'devices') {
      if (key.upArrow) {
        setSelectedDevice((i) => Math.max(0, i - 1))
        setSelectedControl(0)
      } else if (key.downArrow) {
        setSelectedDevice((i) => Math.min(devices.length - 1, i + 1))
        setSelectedControl(0)
      }
      return
    }
    // focus === 'controls'
    if (key.upArrow) {
      setSelectedControl((i) => Math.max(0, i - 1))
    } else if (key.downArrow) {
      setSelectedControl((i) => Math.min(controlEntries.length - 1, i + 1))
    } else if (key.return) {
      void invokeSelectedControl()
    }
  })

  async function invokeSelectedControl(): Promise<void> {
    if (currentDevice === undefined || currentEntry === undefined) return
    const pair = controlEntries[selectedControl]
    if (pair === undefined) return
    const [name, descriptor] = pair
    if (Object.keys(descriptor.params).length > 0) {
      setStatus(`${currentEntry.name}.${name} needs params — use CLI for now`)
      return
    }
    if (descriptor.requires === 'active' && !active) {
      setStatus(`${currentEntry.name}.${name} needs --active (press 'a' to arm)`)
      return
    }
    setStatus(`invoking ${currentEntry.name}.${name}…`)
    try {
      await descriptor.invoke(currentDevice, {})
      setStatus(`ok ${currentEntry.name}.${name}`)
    } catch (err) {
      setStatus(`err: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  return (
    <Box flexDirection="column">
      <Box>
        <DeviceList
          devices={devices}
          selectedIndex={selectedDevice}
          focused={focus === 'devices'}
        />
        {currentDevice && currentEntry ? (
          <StatePane
            device={currentDevice}
            controls={currentEntry.controls}
            controlIndex={selectedControl}
            focused={focus === 'controls'}
          />
        ) : null}
      </Box>
      <EventLog entries={log} rows={10} />
      <Footer port={port} active={active} status={status} />
    </Box>
  )
}

// apps/web/src/App.svelte
<script lang="ts">
import type { Device } from '@emdzej/ibusx-core'
import { onMount } from 'svelte'
import ConnectScreen from './lib/components/ConnectScreen.svelte'
import DeviceList from './lib/components/DeviceList.svelte'
import EventLog from './lib/components/EventLog.svelte'
import StatePane from './lib/components/StatePane.svelte'
import Toolbar from './lib/components/Toolbar.svelte'
import { type Connection, connect } from './lib/connection.js'
import { LOG_CAPACITY, type LogEntry } from './lib/log.js'
import type { DeviceEntry } from './lib/registry.js'
import {
  CONFIG_KEY,
  DEFAULT_CONFIG,
  type IbusxConfig,
  loadConfig,
  saveConfig,
} from './lib/storage.js'

let config = $state<IbusxConfig>({ ...DEFAULT_CONFIG, ...loadConfig<IbusxConfig>(CONFIG_KEY) })
let connection = $state<Connection | undefined>(undefined)
let connectError = $state<string | undefined>(undefined)
let log = $state<LogEntry[]>([])
let stateTick = $state(0)
let selectedDeviceIndex = $state(0)

onMount(() => {
  const supported = typeof navigator !== 'undefined' && 'serial' in navigator
  if (!supported) {
    connectError = 'Web Serial is unavailable.  Use Chrome, Edge, or Opera on HTTPS or localhost.'
  }
})

$effect(() => {
  saveConfig<IbusxConfig>(CONFIG_KEY, config)
})

async function handleConnect(port: SerialPort): Promise<void> {
  connectError = undefined
  try {
    connection = await connect({
      port,
      baudRate: config.baudRate,
      onLog: (entry) => {
        log = appendLog(log, entry)
      },
      onDeviceEvent: () => {
        stateTick++
      },
      onClose: () => {
        log = appendLog(log, {
          id: Date.now(),
          kind: 'system',
          ts: Date.now(),
          message: 'transport closed',
        })
        connection = undefined
      },
    })
    if (config.active && connection !== undefined) {
      for (const d of connection.devices) d.mode = 'active'
    }
    log = appendLog(log, {
      id: Date.now(),
      kind: 'system',
      ts: Date.now(),
      message: `connected to ${connection.portLabel}`,
    })
  } catch (err) {
    connectError = err instanceof Error ? err.message : String(err)
  }
}

async function handleDisconnect(): Promise<void> {
  if (connection === undefined) return
  await connection.close()
  connection = undefined
}

function toggleActive(): void {
  config.active = !config.active
  if (connection === undefined) return
  for (const d of connection.devices) d.mode = config.active ? 'active' : 'passive'
}

async function invokeControl(
  // biome-ignore lint/suspicious/noExplicitAny: heterogeneous generics
  device: Device<any, any>,
  entry: DeviceEntry,
  controlName: string,
  args: Record<string, unknown>,
): Promise<void> {
  const descriptor = entry.controls[controlName]
  if (descriptor === undefined) return
  if (descriptor.requires === 'active' && !config.active) {
    log = appendLog(log, {
      id: Date.now(),
      kind: 'error',
      ts: Date.now(),
      message: `${entry.name}.${controlName} needs active mode — toggle the ACTIVE switch`,
    })
    return
  }
  try {
    // biome-ignore lint/suspicious/noExplicitAny: param type erased at this generic call site
    await descriptor.invoke(device, args as any)
    log = appendLog(log, {
      id: Date.now(),
      kind: 'system',
      ts: Date.now(),
      message: `invoked ${entry.name}.${controlName}`,
    })
  } catch (err) {
    log = appendLog(log, {
      id: Date.now(),
      kind: 'error',
      ts: Date.now(),
      message: `${entry.name}.${controlName}: ${err instanceof Error ? err.message : String(err)}`,
    })
  }
}

function appendLog(arr: LogEntry[], entry: LogEntry): LogEntry[] {
  const next = arr.length >= LOG_CAPACITY ? arr.slice(-LOG_CAPACITY + 1) : arr.slice()
  next.push(entry)
  return next
}

// stateTick exists purely to force re-render of components reading device.state.
// Reference it here so the compiler sees a dependency.
$effect(() => {
  void stateTick
})

let currentEntry = $derived(
  connection !== undefined ? connection.entries[selectedDeviceIndex] : undefined,
)
let currentDevice = $derived(
  connection !== undefined ? connection.devices[selectedDeviceIndex] : undefined,
)
</script>

<header>
  <h1>ibusx</h1>
  <Toolbar
    connected={connection !== undefined}
    active={config.active}
    portLabel={connection?.portLabel ?? '—'}
    onToggleActive={toggleActive}
    onDisconnect={handleDisconnect}
  />
</header>

{#if connection === undefined}
  <ConnectScreen bind:baudRate={config.baudRate} error={connectError} onConnect={handleConnect} />
{:else}
  <main>
    <aside>
      <DeviceList
        entries={connection.entries}
        devices={connection.devices}
        selectedIndex={selectedDeviceIndex}
        onSelect={(i) => (selectedDeviceIndex = i)}
      />
    </aside>
    <section>
      {#if currentDevice && currentEntry}
        <StatePane
          device={currentDevice}
          entry={currentEntry}
          active={config.active}
          onInvoke={(name, args) =>
            currentDevice && currentEntry && invokeControl(currentDevice, currentEntry, name, args)}
        />
      {/if}
    </section>
    <footer>
      <EventLog entries={log} />
    </footer>
  </main>
{/if}

<style>
  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 16px;
    border-bottom: 1px solid var(--border);
    background: var(--bg-elev);
  }

  h1 {
    margin: 0;
    font-size: 16px;
    color: var(--accent);
    letter-spacing: 0.5px;
  }

  main {
    flex: 1;
    display: grid;
    grid-template-columns: 220px 1fr;
    grid-template-rows: 1fr 220px;
    grid-template-areas:
      'aside section'
      'footer footer';
    min-height: 0;
  }

  aside {
    grid-area: aside;
    border-right: 1px solid var(--border);
    overflow-y: auto;
    background: var(--bg-elev);
  }

  section {
    grid-area: section;
    overflow-y: auto;
    padding: 12px 16px;
  }

  footer {
    grid-area: footer;
    border-top: 1px solid var(--border);
    background: var(--bg-elev);
    overflow: hidden;
  }
</style>
