// apps/cli/src/tui/components/DeviceList.tsx
import type { Device } from '@emdzej/ibusx-core'
import { Box, Text } from 'ink'
import type { ReactElement } from 'react'

interface Props {
  // biome-ignore lint/suspicious/noExplicitAny: heterogeneous device generics
  devices: readonly Device<any, any>[]
  selectedIndex: number
  focused: boolean
}

export function DeviceList({ devices, selectedIndex, focused }: Props): ReactElement {
  return (
    <Box
      flexDirection="column"
      borderStyle="round"
      borderColor={focused ? 'cyan' : 'gray'}
      paddingX={1}
      width={20}
    >
      <Text bold {...(focused ? { color: 'cyan' as const } : {})}>
        Devices
      </Text>
      {devices.map((device, i) => {
        const selected = i === selectedIndex
        const addr = `0x${device.address.toString(16).padStart(2, '0').toUpperCase()}`
        const color = selected ? (focused ? 'green' : 'yellow') : undefined
        return (
          <Text
            key={device.address}
            {...(color !== undefined ? { color } : {})}
            inverse={selected && focused}
          >
            {selected ? '▸ ' : '  '}
            {device.name.padEnd(5)} {addr}
          </Text>
        )
      })}
    </Box>
  )
}

// apps/web/src/lib/components/DeviceList.svelte
<script lang="ts">
import type { Device } from '@emdzej/ibusx-core'
import type { DeviceEntry } from '../registry.js'

interface Props {
  entries: readonly DeviceEntry[]
  // biome-ignore lint/suspicious/noExplicitAny: heterogeneous generics
  devices: readonly Device<any, any>[]
  selectedIndex: number
  onSelect: (index: number) => void
}

let { entries, devices, selectedIndex, onSelect }: Props = $props()
</script>

<ul>
  {#each entries as entry, i (entry.name)}
    <li>
      <button
        class:selected={i === selectedIndex}
        onclick={() => onSelect(i)}
      >
        <span class="name">{entry.name}</span>
        <span class="addr">0x{devices[i]?.address.toString(16).padStart(2, '0').toUpperCase()}</span>
      </button>
    </li>
  {/each}
</ul>

<style>
  ul {
    list-style: none;
    margin: 0;
    padding: 8px 0;
  }

  li {
    display: block;
  }

  button {
    display: flex;
    width: 100%;
    align-items: center;
    justify-content: space-between;
    background: transparent;
    border: none;
    border-left: 3px solid transparent;
    border-radius: 0;
    padding: 6px 12px;
    text-align: left;
    cursor: pointer;
    color: inherit;
    font: inherit;
  }

  button:hover {
    background: var(--bg-elev-2);
  }

  button.selected {
    background: var(--bg-elev-2);
    border-left-color: var(--accent);
    color: var(--accent);
  }

  .name {
    font-weight: 600;
  }

  .addr {
    color: var(--fg-muted);
    font-size: 11px;
  }

  button.selected .addr {
    color: var(--accent);
  }
</style>
